development: &generic
  # min_prefix_len: 2
  mem_limit: 128M
  # min_word_len: 2
  enable_star: 1
  min_infix_len: 3
  morphology: stem_enru
  # charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+458"
  charset_table: "0..9, A..Z->a..z, _, @, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451, U+451"
  max_matches: 100000
  per_page: 100000
  # mysql41: 9451

  charset_type: "utf-8"
  expand_keywords: 1

# staging:
#   <<: *generic
#   mysql41: 9452

production:
  <<: *generic
# #   mysql41: 9453

# test:
  # <<: *generic
#   mysql41: 9454
#   quiet_deltas: true
